<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Moq" />
		<PackageReference Include="System.Text.Json" />
		<PackageReference Include="xunit" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
	<PackageReference Include="NArchitecture.Core.Test" />
		<PackageReference Include="Xunit.DependencyInjection" />
		<PackageReference Include="xunit.runner.visualstudio">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="coverlet.collector">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\Src\SES\Application\Application.csproj" />
	</ItemGroup>
	<ItemGroup>
		<Folder Include="Features\" />
		<Folder Include="Mocks\FakeDatas\" />
		<Folder Include="Mocks\Repositories\Auth\" />
	</ItemGroup>
</Project>