// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence.Contexts;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(PostgreSqlDbContext))]
    [Migration("20240604230258_v1.1")]
    partial class v11
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entity.Entities.Infos.Semester", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BeginSemesterDate")
                        .HasColumnType("date")
                        .HasColumnName("begin_semester_date");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_date");

                    b.Property<DateOnly>("EndSemesterDate")
                        .HasColumnType("date")
                        .HasColumnName("end_semester_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id")
                        .HasName("pk_semesters");

                    b.ToTable("semesters", (string)null);
                });

            modelBuilder.Entity("Entity.Entities.Mains.Analysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<char>("AltClass")
                        .HasColumnType("character(1)")
                        .HasColumnName("alt_class");

                    b.Property<int>("BenefitId")
                        .HasColumnType("integer")
                        .HasColumnName("benefit_id");

                    b.Property<int>("ClassAge")
                        .HasColumnType("integer")
                        .HasColumnName("class_age");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_date");

                    b.Property<string>("ExamCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("exam_code");

                    b.Property<string>("ExamSemesterYear")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("exam_semester_year");

                    b.Property<string>("FooterNote")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("footer_note");

                    b.Property<string>("LessonName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lesson_name");

                    b.Property<string>("LessonSession")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lesson_session");

                    b.Property<int>("PrincipalId")
                        .HasColumnType("integer")
                        .HasColumnName("principal_id");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    b.Property<int[]>("RefScorePerQuestions")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("ref_score_per_questions");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer")
                        .HasColumnName("school_id");

                    b.Property<int>("SemesterId")
                        .HasColumnType("integer")
                        .HasColumnName("semester_id");

                    b.Property<int>("StudentQuizAnswerId")
                        .HasColumnType("integer")
                        .HasColumnName("student_quiz_answer_id");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer")
                        .HasColumnName("teacher_id");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id")
                        .HasName("pk_analysis_headers");

                    b.HasIndex("PrincipalId")
                        .HasDatabaseName("ix_analysis_headers_principal_id");

                    b.HasIndex("SchoolId")
                        .HasDatabaseName("ix_analysis_headers_school_id");

                    b.HasIndex("SemesterId")
                        .HasDatabaseName("ix_analysis_headers_semester_id");

                    b.HasIndex("TeacherId")
                        .HasDatabaseName("ix_analysis_headers_teacher_id");

                    b.ToTable("analysis_headers", (string)null);
                });

            modelBuilder.Entity("Entity.Entities.Mains.Benefit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnalysisId")
                        .HasColumnType("integer")
                        .HasColumnName("analysis_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_date");

                    b.Property<int?>("QuizQuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("quiz_question_id");

                    b.Property<string>("ReferenceBenefitComments")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reference_benefit_comments");

                    b.Property<string>("ReferenceBenefitNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reference_benefit_number");

                    b.Property<int>("SubLearningAreaId")
                        .HasColumnType("integer")
                        .HasColumnName("sub_learning_area_id");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id")
                        .HasName("pk_benefits");

                    b.HasIndex("AnalysisId")
                        .HasDatabaseName("ix_benefits_analysis_id");

                    b.HasIndex("QuizQuestionId")
                        .HasDatabaseName("ix_benefits_quiz_question_id");

                    b.HasIndex("SubLearningAreaId")
                        .HasDatabaseName("ix_benefits_sub_learning_area_id");

                    b.ToTable("benefits", (string)null);
                });

            modelBuilder.Entity("Entity.Entities.Mains.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnalysisId")
                        .HasColumnType("integer")
                        .HasColumnName("analysis_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_date");

                    b.Property<string>("ExamCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("exam_code");

                    b.Property<string>("FooterNote")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("footer_note");

                    b.Property<string>("LessonName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lesson_name");

                    b.Property<int>("ReferenceBenefitId")
                        .HasColumnType("integer")
                        .HasColumnName("reference_benefit_id");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer")
                        .HasColumnName("school_id");

                    b.Property<int>("SemesterId")
                        .HasColumnType("integer")
                        .HasColumnName("semester_id");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer")
                        .HasColumnName("teacher_id");

                    b.Property<int?>("TotalScore")
                        .HasColumnType("integer")
                        .HasColumnName("total_score");

                    b.Property<string>("TotalScoreForString")
                        .HasColumnType("text")
                        .HasColumnName("total_score_for_string");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id")
                        .HasName("pk_exams");

                    b.HasIndex("AnalysisId")
                        .HasDatabaseName("ix_exams_analysis_id");

                    b.HasIndex("ReferenceBenefitId")
                        .HasDatabaseName("ix_exams_reference_benefit_id");

                    b.HasIndex("SchoolId")
                        .HasDatabaseName("ix_exams_school_id");

                    b.HasIndex("SemesterId")
                        .HasDatabaseName("ix_exams_semester_id");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_exams_student_id");

                    b.HasIndex("TeacherId")
                        .HasDatabaseName("ix_exams_teacher_id");

                    b.ToTable("exams", (string)null);
                });

            modelBuilder.Entity("Entity.Entities.Mains.LearningArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("ReferenceBenefitId")
                        .HasColumnType("integer")
                        .HasColumnName("reference_benefit_id");

                    b.Property<int>("SubLearningAreaId")
                        .HasColumnType("integer")
                        .HasColumnName("sub_learning_area_id");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id")
                        .HasName("pk_learning_areas");

                    b.HasIndex("ReferenceBenefitId")
                        .HasDatabaseName("ix_learning_areas_reference_benefit_id");

                    b.ToTable("learning_areas", (string)null);
                });

            modelBuilder.Entity("Entity.Entities.Mains.Principal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer")
                        .HasColumnName("school_id");

                    b.Property<int>("SemesterId")
                        .HasColumnType("integer")
                        .HasColumnName("semester_id");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sur_name");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id")
                        .HasName("pk_principals");

                    b.HasIndex("SchoolId")
                        .HasDatabaseName("ix_principals_school_id");

                    b.HasIndex("SemesterId")
                        .HasDatabaseName("ix_principals_semester_id");

                    b.ToTable("principals", (string)null);
                });

            modelBuilder.Entity("Entity.Entities.Mains.QuestionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_date");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<string>("OptionText")
                        .HasColumnType("text")
                        .HasColumnName("option_text");

                    b.Property<int>("QuizQuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("quiz_question_id");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id")
                        .HasName("pk_question_options");

                    b.HasIndex("QuizQuestionId")
                        .HasDatabaseName("ix_question_options_quiz_question_id");

                    b.ToTable("question_options", (string)null);
                });

            modelBuilder.Entity("Entity.Entities.Mains.QuestionScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_date");

                    b.Property<int>("MaxScore")
                        .HasColumnType("integer")
                        .HasColumnName("max_score");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<int?>("StudentQuizAnswerId")
                        .HasColumnType("integer")
                        .HasColumnName("student_quiz_answer_id");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id")
                        .HasName("pk_question_scores");

                    b.HasIndex("StudentQuizAnswerId")
                        .HasDatabaseName("ix_question_scores_student_quiz_answer_id");

                    b.ToTable("question_scores", (string)null);
                });

            modelBuilder.Entity("Entity.Entities.Mains.QuizQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BenefitId")
                        .HasColumnType("integer")
                        .HasColumnName("benefit_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_date");

                    b.Property<int>("ExamId")
                        .HasColumnType("integer")
                        .HasColumnName("exam_id");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question");

                    b.Property<string>("QuestionBody")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_body");

                    b.Property<string>("QuestionImage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_image");

                    b.Property<byte>("QuestionType")
                        .HasColumnType("smallint")
                        .HasColumnName("question_type");

                    b.Property<int?>("ReferenceBenefitId")
                        .HasColumnType("integer")
                        .HasColumnName("reference_benefit_id");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id")
                        .HasName("pk_quiz_questions");

                    b.HasIndex("ReferenceBenefitId")
                        .HasDatabaseName("ix_quiz_questions_reference_benefit_id");

                    b.ToTable("quiz_questions", (string)null);
                });

            modelBuilder.Entity("Entity.Entities.Mains.ReferenceBenefit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_date");

                    b.Property<int>("ExamId")
                        .HasColumnType("integer")
                        .HasColumnName("exam_id");

                    b.Property<int>("LearningAreaId")
                        .HasColumnType("integer")
                        .HasColumnName("learning_area_id");

                    b.Property<string>("ReferenceBenefitName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reference_benefit_name");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer")
                        .HasColumnName("school_id");

                    b.Property<int>("SemesterId")
                        .HasColumnType("integer")
                        .HasColumnName("semester_id");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("integer")
                        .HasColumnName("teacher_id");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id")
                        .HasName("pk_reference_benefits");

                    b.HasIndex("SchoolId")
                        .HasDatabaseName("ix_reference_benefits_school_id");

                    b.HasIndex("SemesterId")
                        .HasDatabaseName("ix_reference_benefits_semester_id");

                    b.HasIndex("TeacherId")
                        .HasDatabaseName("ix_reference_benefits_teacher_id");

                    b.ToTable("reference_benefits", (string)null);
                });

            modelBuilder.Entity("Entity.Entities.Mains.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id")
                        .HasName("pk_schools");

                    b.ToTable("schools", (string)null);
                });

            modelBuilder.Entity("Entity.Entities.Mains.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassAge")
                        .HasColumnType("integer")
                        .HasColumnName("class_age");

                    b.Property<char>("ClassBranch")
                        .HasColumnType("character(1)")
                        .HasColumnName("class_branch");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_date");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("ExamId")
                        .HasColumnType("integer")
                        .HasColumnName("exam_id");

                    b.Property<char>("Gender")
                        .HasColumnType("character(1)")
                        .HasColumnName("gender");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer")
                        .HasColumnName("school_id");

                    b.Property<string>("SchoolNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("school_number");

                    b.Property<int>("SemesterId")
                        .HasColumnType("integer")
                        .HasColumnName("semester_id");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sur_name");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer")
                        .HasColumnName("teacher_id");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id")
                        .HasName("pk_students");

                    b.HasIndex("SchoolId")
                        .HasDatabaseName("ix_students_school_id");

                    b.HasIndex("SemesterId")
                        .HasDatabaseName("ix_students_semester_id");

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("Entity.Entities.Mains.StudentAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AnalysisId")
                        .HasColumnType("integer")
                        .HasColumnName("analysis_id");

                    b.Property<string>("AnswerText")
                        .HasColumnType("text")
                        .HasColumnName("answer_text");

                    b.Property<int?>("BenefitId")
                        .HasColumnType("integer")
                        .HasColumnName("benefit_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_date");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<Guid?>("QuestionOptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_option_id");

                    b.Property<int>("QuizQuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("quiz_question_id");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id")
                        .HasName("pk_student_answers");

                    b.HasIndex("AnalysisId")
                        .HasDatabaseName("ix_student_answers_analysis_id");

                    b.HasIndex("BenefitId")
                        .HasDatabaseName("ix_student_answers_benefit_id");

                    b.HasIndex("QuestionOptionId")
                        .HasDatabaseName("ix_student_answers_question_option_id");

                    b.HasIndex("QuizQuestionId")
                        .HasDatabaseName("ix_student_answers_quiz_question_id");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_student_answers_student_id");

                    b.ToTable("student_answers", (string)null);
                });

            modelBuilder.Entity("Entity.Entities.Mains.StudentQuizAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnalysisId")
                        .HasColumnType("integer")
                        .HasColumnName("analysis_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_date");

                    b.Property<int>("ExamId")
                        .HasColumnType("integer")
                        .HasColumnName("exam_id");

                    b.Property<char[]>("SpecialStatuses")
                        .IsRequired()
                        .HasColumnType("character(1)[]")
                        .HasColumnName("special_statuses");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("student_number");

                    b.Property<int>("TotalScore")
                        .HasColumnType("integer")
                        .HasColumnName("total_score");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id")
                        .HasName("pk_student_quiz_answers");

                    b.HasIndex("AnalysisId")
                        .HasDatabaseName("ix_student_quiz_answers_analysis_id");

                    b.HasIndex("ExamId")
                        .HasDatabaseName("ix_student_quiz_answers_exam_id");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_student_quiz_answers_student_id");

                    b.ToTable("student_quiz_answers", (string)null);
                });

            modelBuilder.Entity("Entity.Entities.Mains.SubLearningArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BenefitId")
                        .HasColumnType("integer")
                        .HasColumnName("benefit_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_date");

                    b.Property<int?>("LearningAreaId")
                        .HasColumnType("integer")
                        .HasColumnName("learning_area_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id")
                        .HasName("pk_sub_learning_areas");

                    b.HasIndex("LearningAreaId")
                        .HasDatabaseName("ix_sub_learning_areas_learning_area_id");

                    b.ToTable("sub_learning_areas", (string)null);
                });

            modelBuilder.Entity("Entity.Entities.Mains.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_date");

                    b.Property<int>("ExamId")
                        .HasColumnType("integer")
                        .HasColumnName("exam_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer")
                        .HasColumnName("school_id");

                    b.Property<int>("SemesterId")
                        .HasColumnType("integer")
                        .HasColumnName("semester_id");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sur_name");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("Id")
                        .HasName("pk_teachers");

                    b.HasIndex("SchoolId")
                        .HasDatabaseName("ix_teachers_school_id");

                    b.HasIndex("SemesterId")
                        .HasDatabaseName("ix_teachers_semester_id");

                    b.ToTable("teachers", (string)null);
                });

            modelBuilder.Entity("ExamQuizQuestion", b =>
                {
                    b.Property<int>("ExamsId")
                        .HasColumnType("integer")
                        .HasColumnName("exams_id");

                    b.Property<int>("QuizQuestionsId")
                        .HasColumnType("integer")
                        .HasColumnName("quiz_questions_id");

                    b.HasKey("ExamsId", "QuizQuestionsId")
                        .HasName("pk_exam_quiz_question");

                    b.HasIndex("QuizQuestionsId")
                        .HasDatabaseName("ix_exam_quiz_question_quiz_questions_id");

                    b.ToTable("exam_quiz_question", (string)null);
                });

            modelBuilder.Entity("StudentTeacher", b =>
                {
                    b.Property<int>("StudentsId")
                        .HasColumnType("integer")
                        .HasColumnName("students_id");

                    b.Property<int>("TeachersId")
                        .HasColumnType("integer")
                        .HasColumnName("teachers_id");

                    b.HasKey("StudentsId", "TeachersId")
                        .HasName("pk_student_teacher");

                    b.HasIndex("TeachersId")
                        .HasDatabaseName("ix_student_teacher_teachers_id");

                    b.ToTable("student_teacher", (string)null);
                });

            modelBuilder.Entity("Entity.Entities.Mains.Analysis", b =>
                {
                    b.HasOne("Entity.Entities.Mains.Principal", "Principal")
                        .WithMany()
                        .HasForeignKey("PrincipalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_analysis_headers_principals_principal_id");

                    b.HasOne("Entity.Entities.Mains.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_analysis_headers_schools_school_id");

                    b.HasOne("Entity.Entities.Infos.Semester", "Semester")
                        .WithMany("Analyses")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_analysis_headers_semesters_semester_id");

                    b.HasOne("Entity.Entities.Mains.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_analysis_headers_teachers_teacher_id");

                    b.Navigation("Principal");

                    b.Navigation("School");

                    b.Navigation("Semester");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Entity.Entities.Mains.Benefit", b =>
                {
                    b.HasOne("Entity.Entities.Mains.Analysis", null)
                        .WithMany("Benefits")
                        .HasForeignKey("AnalysisId")
                        .HasConstraintName("fk_benefits_analysis_headers_analysis_id");

                    b.HasOne("Entity.Entities.Mains.QuizQuestion", null)
                        .WithMany("Benefits")
                        .HasForeignKey("QuizQuestionId")
                        .HasConstraintName("fk_benefits_quiz_questions_quiz_question_id");

                    b.HasOne("Entity.Entities.Mains.SubLearningArea", "SubLearningArea")
                        .WithMany("Benefits")
                        .HasForeignKey("SubLearningAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_benefits_sub_learning_areas_sub_learning_area_id");

                    b.Navigation("SubLearningArea");
                });

            modelBuilder.Entity("Entity.Entities.Mains.Exam", b =>
                {
                    b.HasOne("Entity.Entities.Mains.Analysis", "Analysis")
                        .WithMany()
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exams_analysis_headers_analysis_id");

                    b.HasOne("Entity.Entities.Mains.ReferenceBenefit", "ReferenceBenefit")
                        .WithMany("Exams")
                        .HasForeignKey("ReferenceBenefitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exams_reference_benefits_reference_benefit_id");

                    b.HasOne("Entity.Entities.Mains.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exams_schools_school_id");

                    b.HasOne("Entity.Entities.Infos.Semester", "Semester")
                        .WithMany("Exams")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exams_semesters_semester_id");

                    b.HasOne("Entity.Entities.Mains.Student", "Student")
                        .WithMany("Exams")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exams_students_student_id");

                    b.HasOne("Entity.Entities.Mains.Teacher", "Teacher")
                        .WithMany("Exams")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exams_teachers_teacher_id");

                    b.Navigation("Analysis");

                    b.Navigation("ReferenceBenefit");

                    b.Navigation("School");

                    b.Navigation("Semester");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Entity.Entities.Mains.LearningArea", b =>
                {
                    b.HasOne("Entity.Entities.Mains.ReferenceBenefit", null)
                        .WithMany("LearningAreas")
                        .HasForeignKey("ReferenceBenefitId")
                        .HasConstraintName("fk_learning_areas_reference_benefits_reference_benefit_id");
                });

            modelBuilder.Entity("Entity.Entities.Mains.Principal", b =>
                {
                    b.HasOne("Entity.Entities.Mains.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_principals_schools_school_id");

                    b.HasOne("Entity.Entities.Infos.Semester", "Semester")
                        .WithMany("Principals")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_principals_semesters_semester_id");

                    b.Navigation("School");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("Entity.Entities.Mains.QuestionOption", b =>
                {
                    b.HasOne("Entity.Entities.Mains.QuizQuestion", "QuizQuestion")
                        .WithMany("Options")
                        .HasForeignKey("QuizQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_question_options_quiz_questions_quiz_question_id");

                    b.Navigation("QuizQuestion");
                });

            modelBuilder.Entity("Entity.Entities.Mains.QuestionScore", b =>
                {
                    b.HasOne("Entity.Entities.Mains.StudentQuizAnswer", null)
                        .WithMany("ScorePerQuestions")
                        .HasForeignKey("StudentQuizAnswerId")
                        .HasConstraintName("fk_question_scores_student_quiz_answers_student_quiz_answer_id");
                });

            modelBuilder.Entity("Entity.Entities.Mains.QuizQuestion", b =>
                {
                    b.HasOne("Entity.Entities.Mains.ReferenceBenefit", null)
                        .WithMany("QuizQuestions")
                        .HasForeignKey("ReferenceBenefitId")
                        .HasConstraintName("fk_quiz_questions_reference_benefits_reference_benefit_id");
                });

            modelBuilder.Entity("Entity.Entities.Mains.ReferenceBenefit", b =>
                {
                    b.HasOne("Entity.Entities.Mains.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reference_benefits_schools_school_id");

                    b.HasOne("Entity.Entities.Infos.Semester", "Semester")
                        .WithMany("ReferenceBenefits")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reference_benefits_semesters_semester_id");

                    b.HasOne("Entity.Entities.Mains.Teacher", null)
                        .WithMany("ReferenceBenefits")
                        .HasForeignKey("TeacherId")
                        .HasConstraintName("fk_reference_benefits_teachers_teacher_id");

                    b.Navigation("School");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("Entity.Entities.Mains.Student", b =>
                {
                    b.HasOne("Entity.Entities.Mains.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_students_schools_school_id");

                    b.HasOne("Entity.Entities.Infos.Semester", "Semester")
                        .WithMany("Students")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_students_semesters_semester_id");

                    b.Navigation("School");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("Entity.Entities.Mains.StudentAnswer", b =>
                {
                    b.HasOne("Entity.Entities.Mains.Analysis", null)
                        .WithMany("Questions")
                        .HasForeignKey("AnalysisId")
                        .HasConstraintName("fk_student_answers_analysis_headers_analysis_id");

                    b.HasOne("Entity.Entities.Mains.Benefit", null)
                        .WithMany("QuizQuestions")
                        .HasForeignKey("BenefitId")
                        .HasConstraintName("fk_student_answers_benefits_benefit_id");

                    b.HasOne("Entity.Entities.Mains.QuestionOption", "QuestionOption")
                        .WithMany()
                        .HasForeignKey("QuestionOptionId")
                        .HasConstraintName("fk_student_answers_question_options_question_option_id");

                    b.HasOne("Entity.Entities.Mains.QuizQuestion", "QuizQuestion")
                        .WithMany("StudentAnswers")
                        .HasForeignKey("QuizQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_answers_quiz_questions_quiz_question_id");

                    b.HasOne("Entity.Entities.Mains.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_answers_students_student_id");

                    b.Navigation("QuestionOption");

                    b.Navigation("QuizQuestion");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Entity.Entities.Mains.StudentQuizAnswer", b =>
                {
                    b.HasOne("Entity.Entities.Mains.Analysis", null)
                        .WithMany("StudentQuizAnswers")
                        .HasForeignKey("AnalysisId")
                        .HasConstraintName("fk_student_quiz_answers_analysis_headers_analysis_id");

                    b.HasOne("Entity.Entities.Mains.Exam", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_quiz_answers_exams_exam_id");

                    b.HasOne("Entity.Entities.Mains.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_quiz_answers_students_student_id");

                    b.Navigation("Exam");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Entity.Entities.Mains.SubLearningArea", b =>
                {
                    b.HasOne("Entity.Entities.Mains.LearningArea", null)
                        .WithMany("SubLearningAreas")
                        .HasForeignKey("LearningAreaId")
                        .HasConstraintName("fk_sub_learning_areas_learning_areas_learning_area_id");
                });

            modelBuilder.Entity("Entity.Entities.Mains.Teacher", b =>
                {
                    b.HasOne("Entity.Entities.Mains.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_teachers_schools_school_id");

                    b.HasOne("Entity.Entities.Infos.Semester", "Semester")
                        .WithMany("Teachers")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_teachers_semesters_semester_id");

                    b.Navigation("School");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("ExamQuizQuestion", b =>
                {
                    b.HasOne("Entity.Entities.Mains.Exam", null)
                        .WithMany()
                        .HasForeignKey("ExamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exam_quiz_question_exams_exams_id");

                    b.HasOne("Entity.Entities.Mains.QuizQuestion", null)
                        .WithMany()
                        .HasForeignKey("QuizQuestionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exam_quiz_question_quiz_questions_quiz_questions_id");
                });

            modelBuilder.Entity("StudentTeacher", b =>
                {
                    b.HasOne("Entity.Entities.Mains.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_teacher_students_students_id");

                    b.HasOne("Entity.Entities.Mains.Teacher", null)
                        .WithMany()
                        .HasForeignKey("TeachersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_teacher_teachers_teachers_id");
                });

            modelBuilder.Entity("Entity.Entities.Infos.Semester", b =>
                {
                    b.Navigation("Analyses");

                    b.Navigation("Exams");

                    b.Navigation("Principals");

                    b.Navigation("ReferenceBenefits");

                    b.Navigation("Students");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("Entity.Entities.Mains.Analysis", b =>
                {
                    b.Navigation("Benefits");

                    b.Navigation("Questions");

                    b.Navigation("StudentQuizAnswers");
                });

            modelBuilder.Entity("Entity.Entities.Mains.Benefit", b =>
                {
                    b.Navigation("QuizQuestions");
                });

            modelBuilder.Entity("Entity.Entities.Mains.LearningArea", b =>
                {
                    b.Navigation("SubLearningAreas");
                });

            modelBuilder.Entity("Entity.Entities.Mains.QuizQuestion", b =>
                {
                    b.Navigation("Benefits");

                    b.Navigation("Options");

                    b.Navigation("StudentAnswers");
                });

            modelBuilder.Entity("Entity.Entities.Mains.ReferenceBenefit", b =>
                {
                    b.Navigation("Exams");

                    b.Navigation("LearningAreas");

                    b.Navigation("QuizQuestions");
                });

            modelBuilder.Entity("Entity.Entities.Mains.Student", b =>
                {
                    b.Navigation("Exams");
                });

            modelBuilder.Entity("Entity.Entities.Mains.StudentQuizAnswer", b =>
                {
                    b.Navigation("ScorePerQuestions");
                });

            modelBuilder.Entity("Entity.Entities.Mains.SubLearningArea", b =>
                {
                    b.Navigation("Benefits");
                });

            modelBuilder.Entity("Entity.Entities.Mains.Teacher", b =>
                {
                    b.Navigation("Exams");

                    b.Navigation("ReferenceBenefits");
                });
#pragma warning restore 612, 618
        }
    }
}
