<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AutoMapper" />
    <PackageReference Include="MathNet.Numerics" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="NArchitecture.Core.Application" />
    <PackageReference Include="NArchitecture.Core.Mailing" />
    <PackageReference Include="NArchitecture.Core.Mailing.Mailkit" />
    <PackageReference Include="NArchitecture.Core.CrossCuttingConcerns.Exception" />
    <PackageReference Include="NArchitecture.Core.CrossCuttingConcerns.Logging.Serilog.File" />
    <PackageReference Include="NArchitecture.Core.Localization.Abstraction" />
    <PackageReference Include="NArchitecture.Core.Localization.Resource.Yaml.DependencyInjection" />
    <PackageReference Include="NArchitecture.Core.ElasticSearch" />
    <PackageReference Include="NArchitecture.Core.Security.DependencyInjection" />
    <PackageReference Include="itext7" />
    <PackageReference Include="QuestPDF" />
    <PackageReference Include="SimpleBase" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Features\**\Resources\Locales\*.*.yaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <None Update="Services\AIService\Resources\AIModels.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Services\AIService\Resources\AnalysisPrompt.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Services\AIService\Resources\QuestionPrompt.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Features\Exams\Commands\CreateMultipleExam\DTO\" />
  </ItemGroup>
</Project>